allowBuilds:
  '@nestjs/core': false
  '@prisma/engines': false
  '@scarf/scarf': false
  bcrypt: false
  msgpackr-extract: false
  prisma: false
  puppeteer: true
  sharp: true
  unrs-resolver: false
