export enum PaymentProvider {
  MTN = 'MTN_MOMO_COG',
  AIRTEL = 'AIRTEL_COG',
}

export enum DepositFailureCode {
  ACCEPTED = 'ACCEPTED',
  DUPLICATE_IGNORED = 'DUPLICATE_IGNORED',
  PROVIDER_TEMPORARILY_UNAVAILABLE = 'PROVIDER_TEMPORARILY_UNAVAILABLE',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  AMOUNT_OUT_OF_BOUNDS = 'AMOUNT_OUT_OF_BOUNDS',
}

export enum InitiateDepositStatus {
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  DUPLICATE_IGNORED = 'DUPLICATE_IGNORED',
}

export enum CheckDepositStatus {
  COMPLETED = 'COMPLETED',
  ACCEPTED = 'ACCEPTED',
  PROCESSING = 'PROCESSING',
  IN_RECONCILIATION = 'IN_RECONCILIATION',
  FAILED = 'FAILED',
  NOT_FOUND = 'NOT_FOUND',
}

export interface RejectionReason {
  rejectionCode: DepositFailureCode;
  rejectionMessage: string;
}
